name: data_covid
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  http: 0.13.4
  flutter_native_splash: ^2.0.2
  flutter: 
    sdk: flutter
    

dev_dependencies: 
 flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter_native_splash:
 color: "#F62817"
 image: "assets/icon/images.jpg"
 android: true
 ios: true
 web: true
  
flutter: 
  uses-material-design: true


